Feature/397
10up/distributor pull request #1036
Opened 2023-03-21 12:24 UTC by roshniahuja

Fixes for issue #397 
### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...
Props @roshniahuja 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-03-21 13:03 UTC, roshniahuja commented
@peterwilsoncc ,

I have to Apply condition based Title for PluginDocumentSettingPanel and for that I had created const and added that const in title as below but somehow it is not working. Can you please check once?

> title={ DistributorTitle }

 https://github.com/10up/distributor/blob/88761bed134235ead796ed9b9fa0e651c4182edb/assets/js/gutenberg-plugin.js#:~:text=)%3B-,/**,%7D%3B,-/**

2023-03-21 13:05 UTC, roshniahuja commented
@jeffpaul ,

I have integrated this feature in Modal but Need to setup design so can you please assign one designer for the same?

2023-03-21 17:04 UTC, roshniahuja commented
> @peterwilsoncc ,
> 
> I have to Apply condition based Title for PluginDocumentSettingPanel and for that I had created const and added that const in title as below but somehow it is not working. Can you please check once?
> 
> > title={ DistributorTitle }
> 
> https://github.com/10up/distributor/blob/88761bed134235ead796ed9b9fa0e651c4182edb/assets/js/gutenberg-plugin.js#:~:text=)%3B-,/**,%7D%3B,-/**

@peterwilsoncc , You can ignore this as its been resolved.

2023-06-08 15:20 UTC, ravinderk reviewed
We can hold the review. I raised a question on issue https://github.com/10up/distributor/issues/397#issuecomment-1582799450

2024-07-05 16:45 UTC, faisal-alvi commented
Note:
- The design part is completed.
- Added 3 different icons to show the status of a post. 1. Linked 2. Unlinked 3. Pushed

![image](https://github.com/10up/distributor/assets/25176325/ae9b56e5-d10e-48c2-b69d-ef874873aa44)
(_image also added to the main description_)

E2E failures should be ignored as they will be addressed in https://github.com/10up/distributor/pull/1242.

2024-07-12 14:17 UTC, iamdharmesh requested changes
Thanks for working on this @faisal-alvi. Great work here, I have added 2 minor comments. Also, for me the "Unlink" button is disabled and I am also not able to click (X) on the popup. Could you please help to check?

![image](https://github.com/user-attachments/assets/e42dab32-5fb2-4fd6-ba1b-57b9b91859e6)


Thank you.

2024-07-12 14:17 UTC, iamdharmesh commented on assets/js/gutenberg-plugin.js
> +					,
```suggestion
```

2024-07-12 14:17 UTC, iamdharmesh commented on assets/js/gutenberg-plugin.js
> +					</a>
```suggestion
						{ __( 'Original Content', 'distributor' ) }
					</a>
					{ ', ' }
```

Adding extra space here will fix the spacing issue.
![image](https://github.com/user-attachments/assets/ac49f449-6018-4ba4-b276-b8ceb5837583)

2024-07-14 18:33 UTC, Sidsector9 submitted a review, later dismissed
Tests well 👍 , Approving not merging yet.

@jeffpaul following up on the comment by Ravinder here - https://github.com/10up/distributor/issues/397#issuecomment-1582799450

cc: @dkotter as Jeff is on PTO.

If it's cool with you then it's good to go.

2024-07-15 16:41 UTC, dkotter commented
> following up on the comment by Ravinder here - https://github.com/10up/distributor/issues/397#issuecomment-1582799450

I think I agree that these icons could be clearer but I also don't have a great suggestion in mind. I think we're fine to ship this as-is and we can iterate on it later.

That said, I see there's a couple comments by @iamdharmesh that need addressed and also seeing a bunch of eslint issues we should clean up. Once those are taken care of, I'm good to get this merged in

2024-07-22 19:58 UTC, iamdharmesh approved these changes, later dismissed
Thanks for the changes @faisal-alvi @Sidsector9. LGTM.

Just added a minor suggestion but nothing blocker.

2024-07-22 19:58 UTC, iamdharmesh commented on includes/syndicated-post-ui.php
> +					echo '<a href="' . esc_url( $post_url ) . '"><span title="' . esc_attr__( 'Unlinked', 'distributor' ) . '" class="dashicons dashicons-editor-unlink"></span></span></a>';
Maybe this should also open in a new tab like Linked post?
```suggestion
					echo '<a target="_blank" href="' . esc_url( $post_url ) . '"><span title="' . esc_attr__( 'Unlinked', 'distributor' ) . '" class="dashicons dashicons-editor-unlink"></span></span></a>';
```

2024-07-24 16:14 UTC, iamdharmesh approved these changes

2024-08-20 17:50 UTC, merged