Add categories to pull screen - 2
10up/distributor pull request #1244
Opened 2024-07-09 22:54 UTC by kirtangajjar

### Description of the Change

Add categories to the pull screen. This is part 2 of 2  of this issue. This PR filters posts by categories. 

Closes #428

### How to test the Change

1. Open post pull screen
2. You should be able to see post categories in the filter.
3. Select a category and filter. The posts should be filtered by categories.
4. Pull the posts and verify only posts from that category have been pulled.
5. Verify it on both internal and external connections.
6. Verify it in conjunction with post type filter as well.

### Changelog Entry

> Added - Category filter in pull screen

### Credits

Props @kirtangajjar 

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2024-07-12 14:48 UTC, faisal-alvi requested changes
@kirtangajjar thanks for working on this. I tested and found the category filter does not work. Please check the GIF:

![1244-01](https://github.com/user-attachments/assets/42982d53-abad-4106-b1e6-82a2d004b09e)

When I select `test03`, 0 posts should return as results, but it still shows the post with the `Uncategorised` category.

2025-08-11 13:52 UTC, sanketio commented
@faisal-alvi The issue mentioned in https://github.com/10up/distributor/pull/1244#pullrequestreview-2175094375, should be fixed now. In addition to that, I have removed outputting the filters from the bottom, as it is being rendered with the same HTML id attribute, which is an issue.

One more thing we need to work on, is we will have to update the taxonomy list based on the supported post-types, I think, instead of just outputting all the taxonomies for all the post-types. I will work on it in this PR.

cc: @jeffpaul

2025-08-11 13:57 UTC, sanketio commented
@jeffpaul I think we should also not generalize this only for the category, but give an option (maybe a filter) to allow other taxonomies as well, just a thought! What you say?

2025-08-11 14:44 UTC, sanketio commented
For example, if the `page` post-type does not supports category or any other taxonomies, we shouldn't display the filter. So I think that category (taxonomy in general) filter should be based on post-type supports, instead of just the category or taxonomy.

In addition to that, it should respect the remote site's post-type and not the post-type on the current site.

2025-08-11 15:20 UTC, sanketio commented
Just adding a note about https://github.com/10up/distributor/pull/1244#issuecomment-3174971249, that it's going to be tricky because we will have to generate the taxonomy terms again and again when someone changes the post-type filter. But I think we can get all the terms when creating a post-type filter, so trying it out as of now.

2025-08-11 16:26 UTC, jeffpaul commented
> I think we should also not generalize this only for the category, but give an option (maybe a filter) to allow other taxonomies as well, just a thought! What you say?

Making this filterable so folks with custom taxonomies sounds good to me.

> In addition to that, it should respect the remote site's post-type and not the post-type on the current site.

Since you're filtering terms from a separate site, we should render those in the taxonomy dropdown.  If that term is missing on the current site then it should get added as part of the pull distribution

2025-08-12 12:03 UTC, sanketio commented
After thorough testing I found that the `pull` feature with this PR breaks, and I tried debugging it but it keeps taking more time.

I'm creating new PR to generalize the taxonomy terms filter. :)

2025-08-12 15:21 UTC, sanketio commented
@jeffpaul Just an update, I started working on generalizing taxonomy filter, and it's going pretty good. I think I will be able to complete it by tomorrow. :)

2025-08-12 16:12 UTC, sanketio commented
Created a new PR: https://github.com/10up/distributor/pull/1327 for this, I will continue working on this in that PR.

2025-09-05 11:37 UTC, sanketio commented
@jeffpaul @dkotter This can be closed, as I have merged #1327 to the main PR #1237

2025-09-05 14:05 UTC, closed without merging