Fix code scanning alert #2: DOM text reinterpreted as HTML
10up/distributor pull request #1273
Opened 2024-09-19 18:58 UTC by jeffpaul

Fixes [https://github.com/10up/distributor/security/code-scanning/2](https://github.com/10up/distributor/security/code-scanning/2)

_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

2025-05-19 13:15 UTC, jeffpaul commented
@iamdharmesh bumping this back onto your radar

2025-07-08 15:38 UTC, dkotter requested changes
Bunch of lint errors that need cleaned up here

2025-07-09 02:02 UTC, peterwilsoncc commented on assets/js/admin-pull.js
> +	const baseURL = escapeURLComponent(
This changes the URL from absolute to relative so the search form ends up redirecting to something like the followiong and throwing a 404.:

```
http://ms-distributor.local/wp-admin/http%3A%2F%2Fms-distributor.local%2Fwp-admin%2Fadmin.php%3Fpage%3Dpull%26connection_type%3Dinternal%26connection_id%3D2&pull_post_type=post&status=new&s=loggign
```

2025-07-09 03:19 UTC, peterwilsoncc commented
@jeffpaul @dkotter I've pushed an alternative approach in e5b7a78b34bc2b7b978e2a94d25af86567b4b416.

Instead of pulling the URL from the DOM attribute, the code pulls in an identifier and there's a function to convert that in to a URL. This should protect users from themselves if they copy random code in to their console.

2025-07-09 15:06 UTC, dkotter approved these changes

2025-07-09 15:07 UTC, merged