Better keyboard support for distributor admin menu
10up/distributor pull request #569
Opened 2020-03-26 12:56 UTC by samikeijonen

Fixes #563

## Description of the Change

- Use `<button>` instead of `<div>`.
- Use Core button styles where possible for consistency and better focus styles.
- Use `disabled` attribute when post have been syndicated.

## Alternate Designs

None.

## Benefits

Better keyboard support when using correct semantics out of the box.

## Possible Drawbacks

Complex codebase, needs testing that nothing is broken.

## Verification Process

Distribute and push article using only keyboard. 

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/10up/distributor/blob/develop/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

## Applicable Issues

#563

2020-05-13 05:17 UTC, dinhtungdu requested changes
The code looks good @samikeijonen. There is a small issue that internal connections can't be selected using keyboard because they're still using `div`. Can you please update?

2020-05-13 05:36 UTC, dinhtungdu commented on assets/css/push.css
> -	border-radius: 3px;
we should keep the `border-radius` and `text-shadow` because they're overridden by admin bar style.

2020-05-13 09:17 UTC, samikeijonen commented
@dinhtungdu Unfortunately I have zero hours for updates at the moment.

2020-05-13 11:02 UTC, dinhtungdu commented
@samikeijonen no problem, I will take over this.

2020-05-15 03:33 UTC, dinhtungdu submitted a review, later dismissed

2020-05-15 17:32 UTC, dkotter commented
@dinhtungdu Testing this locally, I'm seeing the connection list break if you have more than 4 connections:

<img width="793" alt="Screen Shot 2020-05-15 at 11 28 51 AM" src="https://user-images.githubusercontent.com/916738/82079121-8c895b80-969f-11ea-98e0-ddf98496e6b4.png">

I believe once there are 5 or more connections, we constrain those to a box that you can scroll through, to keep the list down. Looks like something changed here that is preventing that from working properly, so the entire connection list is shown and there's no way to scroll through them all.

2020-05-16 15:43 UTC, dinhtungdu commented
Thank @dkotter, you're right, the style to handle overflow was removed. I added it again, the list is now working correctly with more than 4 connections.

2020-05-18 16:50 UTC, dkotter approved these changes

2020-05-18 16:50 UTC, dkotter commented
@dinhtungdu Looks good 👍

2020-05-19 00:38 UTC, merged