Fix: show loading indicator after submitting an external connection URL
10up/distributor pull request #601
Opened 2020-06-13 03:38 UTC by dinhtungdu

### Description of the Change
Fixes #595.

Show a spinner and a message indicates that we're checking the connection. 

### Benefits
Make the UI more interactive.

### Possible Drawbacks

### Verification Process
Create a new connection using Auth Wizard, see the spinner and message after submitting the external site URL.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/10up/distributor/blob/develop/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

2020-06-15 22:29 UTC, helen requested changes
Have one string tweak and one other thing I noticed - the checking message shows even with an empty URL and then gets stuck there. I think it probably shouldn't show until it's past the URL checking a few lines later.

2020-06-15 22:29 UTC, helen commented on includes/classes/Authentications/WordPressBasicAuth.php
> +					<span><?php esc_html_e( 'Checking the connection..', 'distributor' ); ?></span>
```suggestion
					<span><?php esc_html_e( 'Checking the connection...', 'distributor' ); ?></span>
```

Should be a full 3-dot ellipsis :)

2020-06-15 23:33 UTC, dinhtungdu commented
@helen Thanks for the review! Now the status only shows after URL and title are validated.

2020-06-16 02:55 UTC, helen approved these changes
Works great now!

2020-06-16 02:55 UTC, merged