Hiding registration notice when it's registered
10up/distributor pull request #702
Opened 2021-01-22 15:44 UTC by dhanendran

### Description of the Change

Fixes https://github.com/10up/distributor/issues/501. This change hides the registration notice when the valid registration key is added.

### Alternate Designs

N/A

### Benefits

This change will help to avoid the confusion of seeing the registration notice even after adding the valid key.

### Possible Drawbacks

N/A

### Verification Process

- Message should be shown when the fields are empty
- Message should be shown when invalid licence key is added
- Message should be hidden when there is a valid licence key

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Applicable Issues

https://github.com/10up/distributor/issues/501

### Changelog Entry

2021-01-22 21:51 UTC, dkotter requested changes

2021-01-22 21:51 UTC, dkotter commented on includes/settings.php
> +	<?php if ( false === $settings['valid_license'] ) : ?>
@dhanendran Nit picky comment but can you fix the indentation on this code block? Basically the paragraph within the `if` statement should be tabbed over one. Thanks!

2021-01-22 21:51 UTC, dkotter commented on includes/settings.php
> +						<?php if ( false === $settings['valid_license'] ) : ?>
Same comment as above

2021-01-22 21:53 UTC, dkotter commented
Thanks for this @dhanendran. Left a minor comment but otherwise this looks good!

2021-01-23 15:25 UTC, dhanendran commented
@dkotter I have addressed the spacing issue.

2021-01-25 03:15 UTC, dinhtungdu requested changes
Hi @dhanendran, thank you for the PR. This PR is hiding the notice when the plugin is first time activated, where the `valid_license` is `null`, not `false`. Otherwise, this is ready to go.

2021-01-25 03:15 UTC, dinhtungdu commented on includes/settings.php
> +						<?php if ( false === $settings['valid_license'] ) : ?>
```suggestion
						<?php if ( true !== $settings['valid_license'] ) : ?>
```

2021-01-25 03:15 UTC, dinhtungdu commented on includes/settings.php
> +	<?php if ( false === $settings['valid_license'] ) : ?>
```suggestion
	<?php if ( true !== $settings['valid_license'] ) : ?>
```

2021-01-25 11:27 UTC, dhanendran commented
@dinhtungdu Thanks for your suggestion. I have made the changes now.

2021-01-25 11:28 UTC, dinhtungdu approved these changes

2021-01-27 17:35 UTC, dkotter approved these changes

2021-01-27 22:41 UTC, merged