Fix/997 reduce push duplication
10up/distributor pull request #999
Opened 2023-01-09 04:43 UTC by peterwilsoncc

### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-02-22 09:46 UTC, cadic requested changes
I've tested this PR and some workflows:

Created a new post on source site with images, categories, tags and custom meta.

|Workflow|Network|External conn|
|-|-|-|
| Push as Draft | ✅ | ✅ |
| Push as Published | ✅ | ✅ |
| Change the original (see changes reflected to copies) | ✅ | ✅ |
| Unlink from the original, make changes, re-link back, see the copy reset to original| ✅ | ✅ |

Works great!

The code looks good, I just have a couple suggestions about the argument type and removing the duplicate user functions from Unit test.

2023-02-22 09:46 UTC, cadic commented on includes/classes/InternalConnections/NetworkSiteConnection.php
>  	public function push( $post_id, $args = array() ) {
Within the current PR, in [WordPressExternalConnection::push()](https://github.com/10up/distributor/pull/999/files#diff-fb0e5652598ac73446e096480da914a26fa59b2e929ecb314b4169ac51ff1d53R604), you've updated the first argument to be `int|WP_Post`. I wonder should we do the same here for consistency?

2023-02-22 09:46 UTC, cadic commented on tests/php/DistributorPostTest.php
> +		\WP_Mock::userFunction( 'switch_to_blog' );
Looks like it's safe to remove the same user functions from lines 166-167 now after they are declared in the setup_common()?

2023-02-22 23:26 UTC, peterwilsoncc commented on includes/classes/InternalConnections/NetworkSiteConnection.php
>  	public function push( $post_id, $args = array() ) {
Excellent idea, pushed in 4b37f89b6fc5b441af315c18080a7b9f0677d984

2023-02-22 23:30 UTC, peterwilsoncc commented on tests/php/DistributorPostTest.php
> +		\WP_Mock::userFunction( 'switch_to_blog' );
Removed in 6d61fb402d50cc7ba078a0a384f31c698d90643b

2023-02-22 23:32 UTC, peterwilsoncc commented
Thanks @cadic -- I've followed up each of your suggestions.

2023-02-23 07:09 UTC, cadic approved these changes

2023-02-24 01:09 UTC, merged